package com.neuedu.dao;

import com.neuedu.pojo.UserInfo;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface UserInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_user
     *
     * @mbg.generated
     */
    int insert(UserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_user
     *
     * @mbg.generated
     */
    UserInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_user
     *
     * @mbg.generated
     */
    List<UserInfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserInfo record);

    /**
     * 检验username是否存在
     * */

    int checkUsername(String username);
    int checkEmail(String email);

/**
 * 根据用户名和密码查询用户信息
 * */
    UserInfo selectUserByUsernameAndPassword(@Param("username") String username,
                                             @Param("password") String password);

    /**
     * 根据用户名查询密码问题
     * */
    String selectQuestionByUsername(String username);

    /**
     * 根据用户名和密码问题、答案查询用户信息
     * */
    int selectByUsernameAndQuestionAndAnswer(@Param("username") String username,
                                             @Param("question") String question,
                                             @Param("answer") String answer);


/**
 * 根据用户名更新密码
 * */

int updatePasswordByUsername(@Param("username") String username,@Param("password") String passwordNew);


/**
 * 根据用户名查询role值
 * */

  int selectByUsernameForRole(@Param("username") String username);


}